### ISSUE TITLE
roles的templates静态文件引用变量，批量递归拷贝

### ISSUE THREAD

**Issue by c1awn** [c1awn/sth#20]
## 背景  
ansible的yml等脚本类文件可直接引用变量，但是如果静态文件类也想引用变量呢？比如某个配置文件config.json。网上大部分教程是在tasks里调用templates模块，而且源文件强调后缀是.j2，且是单个文件的调用。比如下面的：
```
tasks: 
    - name: generation the hello_world.txt file
         template:
              src: hello_world.txt.j2    //src的文件后缀多了.j2
              dest: /tmp/hello_world.txt 
```
如果想批量调用templates呢？roles提供了一种思路。**以下内容适合有一定roles基础的人**   
## 实际需求 
roles/test角色的files需要全部拷贝（目录和文件）。templates下面多个多层级目录下的配置文件要拷贝，且引用vars变量
```
[root@centos7 chawn]# tree roles
roles
├── test
│   ├── files
│   │   ├── AAA  //目录
│   │   └── base.retry   //文件
│   ├── tasks
│   │   └── main.yml
│   ├── templates
│   │   ├── api
│   │   │   ├── config1
│   │   │   │   └── config
│   │   │   │       ├── api1
│   │   │   │       │   └── redis.config.js
│   │   │   │       ├── api2
│   │   │   │       │   └── redis.config.js
│   │   │   │       └── api3
│   │   │   │           └── redis.config.js
│   │   │   └── config2
│   │   │       └── config
│   │   │           ├── api1
│   │   │           │   └── redis.config.js
│   │   │           ├── api2
│   │   │           │   └── redis.config.js
│   │   │           └── api3
│   │   │               └── redis.config.txt
│   │   └── config.ini   //无目录，配置文件后缀随便改一个，作参考
│   └── vars
│       └── main.yml
└── test.yml
```
vars的main.yml
```
cat /home/chawn/roles/test/vars/main.yml
dir: roles_test
api_ip: 192.168.44.100
api_port: 8090
```
tasks的main.yml
```
[root@centos7 test]# cat tasks/main.yml 
---
  - name: mkdir  //copy使用前创建对应目录
    file: dest=/tmp/{{ dir }} state=directory 
  - name: copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode=755
    with_items: 
      - { src: './',dest: '/tmp/{{ dir }}/' }   //src用的./ 表示files下面全部目录和文件
  - name: Approve certs server directories //templates引用当前src环境，在dest创建相同的目录
    file:
      state: directory
      dest: '/tmp/{{ dir }}/{{ item.path }}'  //此处/tmp/{{ dir }}/为自定义
    with_filetree: '../templates'                //关键部分
    when: item.state == 'directory'
  - name: Approve certs server files
    template:
      src: '{{ item.src }}'
      dest: '/tmp/{{ dir }}/{{ item.path }}'    //此处/tmp/{{ dir }}/为自定义
      mode: '{{ item.mode }}'    //templates的dest属性调用src的，不能用755之类的固定值
      owner: '{{ item.owner }}'  //同上
      group: '{{ item.group }}' //同上
    with_filetree: '../templates'   //关键部分
    when: item.state == 'file'
```
test的主入口
```
[root@centos7 roles]# cat test.yml 
- hosts: test
  gather_facts: no
  tasks:
  - name: hello
    shell: echo hello
- hosts: test
  gather_facts: no
  become: yes
  become_method: su
  roles: 
  - test
- hosts: test
  gather_facts: no
  tasks:
  - name: bye
    shell: echo bye
```
部分templates内容
```
[root@centos7 api3]# cat redis.config.txt 
exports.config = {
  host:'{{ api_ip }}',
  port: {{ api_port }},
  db: 0,
  prefix: 'allinone:'
}
[root@centos7 api3]# pwd
/home/chawn/roles/test/templates/api/config2/config/api3
```
```
[root@centos7 templates]# cat config.ini 
path=/tmp/{{ dir }}
[root@centos7 templates]# pwd
/home/chawn/roles/test/templates
```
## 执行结果  
1. files下面的目录和文件全部拷贝成功
```
ll /tmp/roles_test/
total 8
drwxr-xr-x. 2 root root  6 Dec  7 10:02 AAA   //files下面的目录
drwxr-xr-x. 4 root root 36 Dec  7 10:02 api   //templates下面的目录
-rwxr-xr-x. 1 root root 15 Dec  7 10:01 base.retry //files下面的文件
-rw-r--r--. 1 root root 21 Dec  7 10:02 config.ini //templates下面的文件
```
2. templates下面所有配置拷贝成功，且变量值符合vars定义，此条件下的模板后缀无所谓。
```
[root@centos7-2 roles_test]# cat config.ini 
path=/tmp/roles_test
```
```
[root@centos7-2 roles_test]# cat api/config2/config/api3/redis.config.txt 
exports.config = {
  host:'192.168.44.100',
  port: 8090,
  db: 0,
  prefix: 'allinone:'
}
```
