### ISSUE TITLE
ansible-playbook创建sudoer用户

### ISSUE THREAD

**Issue by c1awn** [c1awn/sth#23]
>user是用户、123456是密码，需要替换为真实参数
"user ALL=(ALL)  NOPASSWD:ALL "是免密sudo，不想免密就改成"user ALL=(ALL)  ALL "
"Defaults: user !requiretty" 屏蔽sudo提示
validate: 'visudo -cf %s'，在一些场景下，我们修改完文件后，需要对文件做一下测试，用以检查文件修改之后，是否能正常运行。如http.conf、nginx.conf等，一旦改错，而不加以测试，可能会直接导致http服务挂掉

```
---
- hosts: test
  tasks:
   - name: create user
     user:
       name: "{{item.user}}"
       password: "{{ item.pass | password_hash('sha512') }}"
       createhome: yes
       state: present
       shell: "/bin/bash"     
     loop:
      - { user: user,pass: 123456 }
   - name: Config /etc/sudoers
     lineinfile: dest=/etc/sudoers state=present line='{{item}}'  validate='visudo -cf %s'
     with_items:
         - "user ALL=(ALL)  NOPASSWD:ALL "
         - "Defaults: user !requiretty"
```
- 下面是shell脚本参考
```
#!/bin/sh  
USERNAME=xxx
PASS=xxx

if id -u ${USERNAME} >/dev/null 2>&1 ; then
    echo "User ${USERNAME} exists."
else
    echo "User ${USERNAME} does not exist!"
	useradd  $USERNAME -u 1111
        echo $PASS | sudo passwd $USERNAME --stdin  &>/dev/null
fi

#追加用户至sudoers设置sudo免密调用
sed -i '/^root.*ALL=(ALL).*ALL/a\'$USERNAME'\tALL=(ALL) \tNOPASSWD:ALL' /etc/sudoers
names=`cat /etc/sudoers | grep -w $USERNAME| wc -l`
if [ $names -eq 0 ];then
    echo -e "\033[31m用户$USERNAME:sudoers修改失败，请检验\033[0m"
else
    echo -e "\033[32m用户$USERNAME:sudoers修改成功\033[0m"
fi
```
