### ISSUE TITLE
ansible with_items copy文件-追加配置

### ISSUE THREAD

**Issue by c1awn** [c1awn/sth#24]
下面是对copy文件、追加配置语句一个场景：定义一个用户登录脚本（执行预期的命令），再用bashrc调用
```
---
- hosts: test
  remote_user: root
  gather_facts: false
  tasks:
    - name: copy file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: user
        group: user
        mode: 755
      with_items:
      - {src: "./.post_login.sh", dest: "/home/user/.post_login.sh" }
    - name: append file
      lineinfile: dest=/home/user/.bashrc state=present line='{{item}}' 
      with_items:
         - "/bin/bash ~/.post_login.sh"

```
